Add get-muted command
jonhoo/obs-do pull request #29
Opened 2024-12-18 16:59 UTC by GaetanLepage

This adds a simple `get-mute` command.

2024-12-27 14:10 UTC, jonhoo requested changes
Thank you! Looks good except for the one comment.

2024-12-27 14:10 UTC, jonhoo commented on src/main.rs
> +            let muted = client.inputs().muted(InputId::Name(&input)).await?;
Let's add a `.context()` like in the other match arms

2024-12-29 00:03 UTC, GaetanLepage commented on src/main.rs
> +            let muted = client.inputs().muted(InputId::Name(&input)).await?;
I am not sure how here... You  want to print the result value by chaining a `.context()` on this request ?
We don't have the response at this stage, right ?
Or simply a message saying "Determining if input <INPUT> is muted" ?

2024-12-30 09:45 UTC, jonhoo commented on src/main.rs
> +            let muted = client.inputs().muted(InputId::Name(&input)).await?;
Exactly the same as we do for toggle-mute for example (you may need to pull):
https://github.com/jonhoo/obs-do/blob/131f707a15f8a435128ee2f6c07a44e7e6ae8832/src/main.rs#L125-L129

2024-12-30 22:08 UTC, GaetanLepage commented on src/main.rs
> +            let muted = client.inputs().muted(InputId::Name(&input)).await?;
Thanks for the pointer. Is that fine like this ?

2024-12-31 08:26 UTC, jonhoo approved these changes
Perfect, thank you!

2024-12-31 08:27 UTC, merged

2024-12-31 08:29 UTC, jonhoo commented
Released in 0.1.6 :tada:

2024-12-31 08:31 UTC, GaetanLepage commented
> Released in 0.1.6 🎉

Thank you !